### ISSUE TITLE
Gateway node metrics error

### ISSUE THREAD

**Issue by patogit** [libremesh/lime-app#137]
On the gateway node in a 3-node network that's a chain Antenna-to-Internet<->A<->B<->C all via cable. Using Chrome on Android 6 or using Firefox on Linux, clicking on "metrics" works for nodes B and C, but for node A gives an error... just a red box that says "Error:" at the top of the page, and the three flashing dots keep flashing and nothing else happens.

**Comment by gmarcos87** [comment]
The problem is in this line https://github.com/libremesh/lime-packages-ui/blob/dd0369b39fabf4b2a6fc6a5f232b0b984c9fd813/packages/ubus-lime-metrics/files/usr/libexec/rpcd/lime-metrics#L90
Returns a null value, because if it is a gateway there is no default dev.
I'm researching how it can be turned around. @nicoechaniz or @nicopace any clue?
