### ISSUE TITLE
Cambio en el nombre de nodo

### ISSUE THREAD

**Issue by comunarr** [libremesh/lime-app#253]
Buen día, estoy trabajando en un libre router con bin 1.2, y en el lime-app, en la sección de administrador, no me permite hacer el cambio de nombre de nodo.  Al poner el nuevo nombre de nodo y dar clik en "Cambiar" aparece un recuadro que dice "Aplicando cambios, el equipo puede no responer por un minuto".  Después de un tiempo, regresa a http://thisnode.info/app/#/admin sin haber hecho el cambio.
Saludos

**Comment by germanferrero** [comment]
@comunarr gracias por reportar este problema.
Se introdujo en este PR: https://github.com/libremesh/lime-packages/pull/515 que cambio la API en lime-utils y no se realizó el cambio correspondiente en la LimeApp

@comunarr thanks for reporting this issue.
The bug was introduced https://github.com/libremesh/lime-packages/pull/515 which changed the API of lime-utils and the corresponding change in the limeapp was not made

**Comment by germanferrero** [comment]
This bug has been fixed by https://github.com/libremesh/lime-app/pull/274
