### ISSUE TITLE
Demo website doesn't work

### ISSUE THREAD

**Issue by nicopace** [libremesh/lime-app#46]
https://libremesh.github.io/lime-app/#/

It fails because it tries to talk to a standard websocket insteaad of a secure websocket.

This is because github.io forces requests to go through https

**Comment by gmarcos87** [comment]
The demo site only works if you are connected from a libremesh network with the lime-webui-ng-luci package installed on the nodes. Also due to github pages security policy is only loaded on https, you must accept the "insecure" load from the option in the address bar (in chorme). 

![Accept insecure code secuende](https://image.ibb.co/dQRCHk/Captura_de_pantalla_de_2017_06_26_12_48_02.png)

**Comment by nicopace** [comment]
If connecting to the WebSocket fails, could we add a visible notice about that?

This is something that will happen all the time, and would be helpful to let the user know about it.
